### ISSUE TITLE
不应该是[tool:]而是[re:]

### ISSUE THREAD

**Issue by dewrfe53535** [hufan-akari/lrc-maker#11]
> [re:创建此LRC文件的播放器或编辑器]
[LRC格式 - 维基百科](https://zh.wikipedia.org/wiki/LRC格式)

**Comment by hufan-akari** [comment]
因为 lrc 并没有一个严格的标准。
而无论是 `tool`，还是 `re` ，大部分音乐播放器会直接忽略这个字段。
所以这是我刻意为之的地方，挑选了一个语义更明确单词做字段，给人读，而不是给机器读。

**Comment by hufan-akari** [comment]
因为多出一个字段也并没有什么负面影响，如果你还在纠结的话，你可以认为这里没有`re`，而 `tool` 是另外某个可以忽略的东西。
