### ISSUE TITLE
Lose focus after adjusting the progress bar

### ISSUE THREAD

**Issue by chromezh** [hufan-akari/lrc-maker#3]
首先感谢如此实用的程序！我和我的小伙伴们都非常喜欢！

发现了一个问题：在打轴模式，调整进度条以后，再按下空格键，就不能正常进行打轴，而是页面下翻。此时需要再次点击页面空白区域，才能重新进行打轴。

因为平时在页面上按下空格键，确实应该是页面下翻的，所以这样的现象也可以理解。但是，在做歌词滚动的时候，调整进度条的事情也很常见，如果每次调整了进度条，还需要点击页面空白处才能继续，有点麻烦呢。

不知道这个问题是不是可以被解决的问题，还是我食用的姿势不对呢？ >_<

浏览器：Microsoft Edge

预先感谢！

**Comment by hufan-akari** [comment]
如果还有问题, 请 reopen issue 并反馈给我信息.

**Comment by chromezh** [comment]
已经解决了🎉～
